darcs pull

diff --git a/src/Makefile.defs b/src/Makefile.defs
--- a/src/Makefile.defs
+++ b/src/Makefile.defs
@@ -12,20 +12,16 @@ export CHECKSUM
 export CC99
 export CFLAGS
 export CC
-
 QCC = $(BASILISK)/qcc
 
 check: $(subst .c,.tst,$(filter-out $(TESTS),$(filter-out $(EXCLUDE),$(ALLTESTS)))) Makefile.deps
 
 tags: $(subst .page,.tags,$(ALLPAGES))
 
-itags: $(subst .h.page,.h.itags,$(ALLPAGES))
-
-links:
-	sh $(BASILISK)/links.sh
+itags: $(subst .page,.itags,$(filter %.h.page, $(ALLPAGES)))
 
 clean:
-	rm -f *.o *.s *.*tst *.d *.prof Makefile.deps
+	rm -f *.o *.s *.*tst *.d *.prof *.itags Makefile.deps Makefile.tests
 
 .PRECIOUS: %.prof %.s %.c %.h %.plot
 
@@ -36,47 +32,55 @@ clean:
 
 %.3D.tst: %.3D.s %.3D.c
 	@CFLAGS="$(CFLAGS) -grid=octree" LIBS="$(LIBS)" OPENGLIBS="$(OPENGLIBS)"\
-		$(BASILISK)/runtest $@
+		GDB="$(GDB)" $(BASILISK)/runtest $@
 
 %.CADNA.c: %.c
 	ln -s $< $@
 
 %.CADNA.tst: %.CADNA.s %.CADNA.c
 	@CFLAGS="$(CFLAGS) -cadna" LIBS="$(LIBS) $(CADNALIBS)" OPENGLIBS="$(OPENGLIBS)"\
-		$(BASILISK)/runtest $@
+		GDB="$(GDB)" $(BASILISK)/runtest $@
 
 %.tst: %.s %.c
 	@PNG=$(PNG) LIBS="$(LIBS)" OPENGLIBS="$(OPENGLIBS)" \
-		$(BASILISK)/runtest $@
+		GDB="$(GDB)" $(BASILISK)/runtest $@
 
 %.ctst: %.s %.c
 	@PNG=$(PNG) LIBS="$(LIBS)" OPENGLIBS="$(OPENGLIBS)" \
 		CFLAGS="-grid=multigrid $(CFLAGS)" \
-		$(BASILISK)/runtest $@
+		GDB="$(GDB)" $(BASILISK)/runtest $@
 
 %.vtst: %.s %.c
 	@PNG=$(PNG) LIBS="$(LIBS)" OPENGLIBS="$(OPENGLIBS)" \
 		EXEC="$(VALGRIND)" \
-		$(BASILISK)/runtest $@
+		GDB="$(GDB)" $(BASILISK)/runtest $@
 
-%.h: %.h.page
-	ln -s -f $< $@
+define compile_failed =
+(mkdir -p $* && 										\
+	echo "qcc -autolink $(CFLAGS) -o $*/$* $*.c $(LIBS) -lm" > $*/fail &&			\
+	cat $*.log~ >> $*/fail &&								\
+	echo "make: *** [$*.s] Error 1" >> $*/fail &&						\
+	rm -f $*.*tst &&									\
+	$(GENSUM) $*.c > $*/fail.tst &&								\
+	cat $*/fail 2> /dev/stderr &&								\
+	exit 1)
+endef
 
-%.c: %.c.page
-	ln -s -f $< $@
-
-%.plot: %.plot.page
-	ln -s -f $< $@
-
-%.3D.s: %.3D.c $(QCC) Makefile
+%.3D.s: %.3D.c $(QCC)
 	@echo qcc -autolink $(CFLAGS) -grid=octree -o $*/$* $*.c $(LIBS) -lm
-	@rm -f $*/warn
-	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS) -grid=octree)) $< -o $@ $(LIBS) -lm
+	@rm -f $*/fail $*/warn
+	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS) -grid=octree)) $< -o $@ $(LIBS) -lm 2> $@.log~ || $(compile_failed)
+	@chmod -x $@
+	@test -s $*.log~ && mkdir -p $* && cat $*.log~ > $*/warn
+	@rm -f $*.log~ $*/fail
 
-%.s: %.c $(QCC) Makefile
+%.s: %.c $(QCC)
 	@echo qcc -autolink $(CFLAGS) -o $*/$* $*.c $(LIBS) -lm
-	@rm -f $*/warn
-	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS))) $< -o $@ $(LIBS) -lm
+	@rm -f $*/fail $*/warn
+	@OPENGLIBS="$(OPENGLIBS)" $(QCC) -autolink -nolineno $(STRIPFLAGS) $(subst -g ,,$(subst -O2 ,,$(CFLAGS))) $< -o $@ $(LIBS) -lm 2> $*.log~ ||  $(compile_failed)
+	@chmod -x $@
+	@test -s $*.log~ && mkdir -p $* && cat $*.log~ > $*/warn
+	@rm -f $*.log~ $*/fail
 
 %.prof: %.c
 	$(QCC) -autolink $(subst -DTRASH=1,,$(CFLAGS)) -g -no-pie -pg $< -o $*/$* -lm
@@ -89,9 +93,11 @@ clean:
 %.dot.png: %.dot
 	dot -Tpng -o $@ < $<
 
+# fixme: this is obsolete
 %/plot.png: %.plot
 	cd $* && gnuplot -e "batch=1; PNG=\"$(PNG)\"; set term $(PNG) enhanced font \",10\"; set output 'plot.png'; set macros;" ../$< || rm -f plot.png
 
+# warning: if this recipe is changed, runtest needs to be updated
 %/plots: %.c $(BASILISK)/gnuplot.awk $(BASILISK)/python.awk \
 		$(BASILISK)/gnuplot.sh
 	cd $* && awk -f $(BASILISK)/gnuplot.awk < ../$*.c > plots && \
@@ -109,17 +115,12 @@ clean:
 %.pdf: %.c
 	pandoc -o $@ $<
 
-%.tags: %.page $(QCC)
+%.tags: % $(QCC)
 	$(QCC) -tags $<
-	ln -s -f $< $*
-	( ! test -d $(BASILISK_WIKI)/cache ) || \
-	rm -f $(subst $(BASILISK_WIKI),$(BASILISK_WIKI)/cache,$(PWD))/$<
 
 %.itags: %.tags $(subst .page,.tags,$(ALLPAGES)) $(BASILISK)/includedin.sh
 	sh $(BASILISK)/includedin.sh $* > $@
 	rm -f $*.html
-	( ! test -d $(BASILISK_WIKI)/cache ) || \
-	rm -f $(subst $(BASILISK_WIKI),$(BASILISK_WIKI)/cache,$(PWD))/$(subst .tags,.page,$<)
 
 # lists external symbols of executables
 extern = nm -u $(1) | sed -n 's/^[ ]*U \(.*\)/\1/p' | sort | uniq
@@ -136,7 +137,16 @@ whitelist: $(subst .c,.exe,$(filter-out $(EXCLUDE),$(ALLTESTS))) \
 		grep 'not whitelisted' && rm -f $@ ) || cp -f $< $@
 	@test -f $@
 
+# Octave code
+
+%.s: %.m
+	touch $@
+
+%.tst: %.s %.m
+	$(BASILISK)/runtest $@
+
 # python modules
+
 %.i: %.c $(QCC) $(BASILISK)/python.h
 	$(QCC) $(CFLAGS) -python -c $(MDFLAGS) -I$(PYTHONINCLUDE) $<
 
@@ -146,11 +156,20 @@ whitelist: $(subst .c,.exe,$(filter-out $(EXCLUDE),$(ALLTESTS))) \
 	$(CC) -shared $*.o $*_wrap.o -o _$*.so
 
 # HTML
-%.html: %.page %.tags $(BASILISK)/Makefile.defs 	\
-		$(BASILISK)/templates/page.static 	\
-		$(BASILISK)/plugins/literate-c		\
-		$(BASILISK)/plugins/codeblock		\
-		$(BASILISK)/page2html
+.SECONDEXPANSION:
+%.html: % %.tags $(BASILISK)/Makefile.defs                \
+		$(BASILISK)/darcsit/basilisk.conf         \
+		$(BASILISK)/darcsit/darcsit.conf 	  \
+		$(BASILISK)/darcsit/templates/page.static \
+		$(BASILISK)/darcsit/literate-c		  \
+		$(BASILISK)/darcsit/codeblock		  \
+		$(BASILISK)/darcsit/filetype		  \
+		$(BASILISK)/darcsit/pagemagic		  \
+		$(BASILISK)/darcsit/decl_anchors.awk	  \
+		$(BASILISK)/page2html			  \
+		$$(wildcard $$(subst .c,,%)/warn)	  \
+		$$(wildcard $$(subst .c,,%)/fail)	  \
+		$$(wildcard $$(subst .c,,%)/pass)
 	$(BASILISK)/page2html $< > $@
 	@test -s $@ || exit 1
 
@@ -163,17 +182,17 @@ LINKCHECKER = linkchecker --no-warnings --no-status --anchors	\
 	$(LINKCHECKER) -r 1 $<
 
 # generated makefiles
-Makefile.tests: Makefile $(BASILISK)/tests.sh
+Makefile.tests: $(BASILISK)/tests.sh
 	sh $(BASILISK)/tests.sh
 
 %.s.d: %.c $(QCC)
 	$(QCC) -MD -o $@ $<
 
-%.tags.d: %.page $(QCC)
-	$(QCC) -MD -tags $<
+%.tags.d: % $(QCC)
+	$(QCC) -MD -tags -o $@ $<
 
 Makefile.deps: 	Makefile.tests \
-		$(subst .c,.s.d,$(filter-out $(EXCLUDE),$(ALLTESTS) $(TESTS))) \
+		$(subst .c,.s.d,$(wildcard $(filter-out $(EXCLUDE),$(ALLTESTS) $(TESTS)))) \
 		$(subst .page,.tags.d,$(ALLPAGES))
 	@echo "updating Makefile.deps"
 	@cat /dev/null $^ > Makefile.deps
diff --git a/src/runtest b/src/runtest
--- a/src/runtest
+++ b/src/runtest
@@ -3,11 +3,30 @@
 FILE="$1"
 test="${FILE%.*}"
 ext="${FILE##*.}"
+
+TIMEOUT="timeout --preserve-status 1h"
+
+if test -n "$HTTP_LOGFILE"; then
+    exec 2>> "$HTTP_LOGFILE"
+fi
+
+# for debugging
+# BASH_XTRACEFD=2
+# set -x
+
+if test -f $test.c; then
+    src=$test.c
+elif test -f $test.m; then
+    src=$test.m
+else
+    echo "No source file found for $test" >&2
+    exit 1
+fi
+
 case $ext in
     ctst) log=clog; out=cout; ref=cref; ;;
     *)    log=log;  out=out; ref=ref; ;;
 esac
-dir=`echo $PWD | sed "s:$BASILISK_WIKI/::"`
 
 case $CC in
     *-D_MPI=*) test -z "$EXEC" && EXEC="mpirun -np "`echo $CC | sed 's/.*-D_MPI=\([0-9]*\).*/\1/'`;
@@ -19,9 +38,18 @@ for opt in $CFLAGS; do
     esac
 done
 
+case $OSTYPE in
+    *darwin*) ;; # gdb is (often) broken on Apple OSX
+    *)
+	if test -z "$GDB"; then
+	    GDB=`which gdb`
+	fi
+	;;
+esac
+
 script()
 {
-    rm -f $test.c
+    rm -f $src
     if test -f fail; then
 	return 1
     fi
@@ -30,17 +58,17 @@ script()
 
     pass=true
     rm -f log-* stencil stencil-* fine fine-* coarse coarse-*
-    if test -n "$EXEC" -o -z "`which gdb`"; then
+   if test -n "$EXEC" -o -z "$GDB"; then
 	if ! $EXEC ./$test 2> $log > $out; then
 	    pass=false
-	    if test "$EXEC" = " " -a -f core -a -n "`which gdb`"; then
+	    if test "$EXEC" = " " -a -f core -a -n "$GDB"; then
 		cat $log
 		xterm -e "gnuplot plot -" &
-		gdb -q ./$test core
+		$GDB -q ./$test core
 	    fi
 	fi
-    else
-	if ! gdb -batch -return-child-result -ex "run 2> $log > $out" ./$test > gdb.log 2> gdb.err; then
+   else
+	if ! $GDB -batch -return-child-result -ex "run 2> $log > $out" ./$test > gdb.log 2> gdb.err; then
 	    pass=false
 	    awk '
      {
@@ -81,56 +109,137 @@ script()
     touch pass
 }
 
-expirecache()
-{
-    rm -f $BASILISK_WIKI/cache/$dir/$test.c.page
-}
-
-# run locally
+# run locally (C code)
 locally()
 {
     echo \[$test.$ext\]
-    qcc -autolink $CFLAGS -o $test/$test $test.c $LIBS -lm > $test/warn 2>&1 \
+    $BASILISK/qcc -autolink $CFLAGS -o $test/$test $src $LIBS -lm > $test/warn 2>&1 \
 	|| mv -f $test/warn $test/fail
     cd $test
     script
-    expirecache
     cd ..
 }
 
+# run locally (Octave code)
+locally_octave()
+{
+    echo \[$test.$ext\]
+    cd $test
+    if octave-cli --path .. -W -H -q $src 2> $log > $out; then
+	touch pass
+    else
+	cp -f $log fail
+    fi
+    cd ..
+}
+
+# run untrusted code using the 'basilisk-untrusted' user if it exists
+run_untrusted()
+{
+    status=0
+    if test -n "$chksum"; then
+	if grep -q basilisk-untrusted /etc/passwd; then
+	    if ! mkdir -m 777 ../$chksum; then
+		return 1
+	    fi
+	    if ! sudo -n -u basilisk-untrusted -- \
+		 bash -c "cp -arf * ../$chksum && cd ../$chksum && $1"; then
+		status=1
+	    fi
+	    if ! cp -arf ../$chksum/* .; then
+		status=1
+	    fi
+	    sudo -n -u basilisk-untrusted -- rm -rf ../$chksum/*
+	    rm -r -f ../$chksum
+	else
+	    echo "Could not find the 'basilisk-untrusted' user" >2
+	    status=1
+	fi
+    fi
+    return $status
+}
+
+doplots()
+{
+    if test -f "$1".plot && ! run_untrusted 'gnuplot -e "batch=1; PNG=\"'$PNG'\"; set term '$PNG' enhanced font \",10\"; set output \"plot.png\"; set macros;" '$1'.plot > tmp 2>&1;'; then
+        cat tmp >> warn
+    fi
+    if ! run_untrusted "PNG=$PNG sh $BASILISK/gnuplot.sh $1 > tmp 2>&1"; then
+	cat tmp >> warn
+    fi
+    if ! run_untrusted "MPLBACKEND=Agg python plots.py > tmp 2>&1"; then
+	cat tmp >> warn
+    fi
+    rm -f tmp
+}
+
 # compile/run on a remote "sandbox"
+# NOTE: update remotely_octave() when changing this
 remotely()
 {
     rhost=$1
-    autolink=`qcc -autolink -source $CFLAGS $test.c`
-    chksum=`$GENSUM $test.s | cut -d' ' -f1`.$ext
+    autolink=`$BASILISK/qcc -autolink -progress -source $CFLAGS $src`
+    chksum=`(cat $test.s && pwd && echo $test) | $GENSUM | cut -d' ' -f1`.$ext
     mkdir $test/$chksum
-    mv -f _$test.c $test/$test.c
     cd $test
+    run=`echo $test | sed 's/^~//'`
+    if test "$run" != "$test"; then
+	cp -f $run.* $chksum 2> /dev/null || true
+    fi
     cp -f $test.* $chksum 2> /dev/null || true
-    rm -f $chksum/$test.c.page
+    rm -f $chksum/$src.html
+    if test `echo "$test" | sed 's/^~//'` != "$test"; then
+	cd $chksum
+	for f in "$test".*; do
+	    mv -f "$f" `echo "$f" | sed 's/^~//'`
+	done
+	cd ..
+    fi
+    mv -f ../_$src $chksum/$src
     PCC="\$CC99"
     case "$CFLAGS" in
 	*-cadna*) PCC="\$CADNACC" ;;
     esac
-    PCFLAGS=`echo $CFLAGS | sed -e 's/-grid=[^-]*//' -e 's/-cadna//'`
+    PCFLAGS=`echo $CFLAGS | sed -e 's/-grid=[^-]*//' -e 's/-cadna//' -e 's/-progress//'`
     NCORES=`echo $EXEC | awk 'BEGIN{ np = 1 }{
       if ($1 == "mpirun") np = $3; }END{ print np;}'`
-    cat <<EOF >$chksum/$test.sh
+    case "$CFLAGS" in
+	*-fopenmp*)
+	    NCORES=8
+	    TIMEOUT="OMP_NUM_THREADS=8 $TIMEOUT"
+	    ;;
+    esac
+    cat <<EOF >$chksum/$chksum.sh
 #!/bin/sh
-$PCC $PCFLAGS -I\$HOME/include -o $test $test.c -L\$HOME/lib $LIBS $autolink -lm > warn 2>&1 || mv -f warn fail
-rm -f $test.c
+
+run_untrusted()
+{
+  status=0
+  notrust=/tmp/$chksum
+  if ! sudo -n -u basilisk-untrusted -- bash -c "source /home/basilisk/.bashrc && mkdir \$notrust && cp -arf * \$notrust && cd \$notrust && rm -f completing && \$1 && touch completing"; then
+     status=1
+  fi
+  if ! cp -arf \$notrust/* .; then
+     status=1
+  fi
+  sudo -n -u basilisk-untrusted -- rm -rf \$notrust/
+  return \$status
+}
+
+$PCC $PCFLAGS -I\$HOME/include -o $chksum $src -L\$HOME/lib $LIBS $autolink -lm > warn 2>&1 || mv -f warn fail
+rm -f $src
 if ! test -f fail; then
   test -s warn || rm -f warn
 
   pass=true
   if test -n "$EXEC" -o -z "`which gdb`"; then
-    if ! timeout 1h $EXEC ./$test 2> $log > $out; then
+    if ! run_untrusted "$TIMEOUT $EXEC ./$chksum 2> $log > $out"; then
        pass=false
     fi
   else
-    if ! timeout 1h gdb -batch -return-child-result -ex "run 2> $log > $out" ./$test > gdb.log 2> gdb.err; then
+    if ! run_untrusted "$TIMEOUT gdb -batch -return-child-result -ex \"run 2> $log > $out\" $chksum > gdb.log 2> gdb.err" > gdb.log 2> gdb.err; then
        pass=false
+       cat gdb.err >> $log
        awk '
        {
          if (NF > 0)
@@ -143,7 +252,7 @@ if ! test -f fail; then
        ' < gdb.log >> $log
     fi
     rm -f gdb.log
-  fi
+  fi    
 
   if test -f log-1; then
       mv -f $log log-0
@@ -162,65 +271,148 @@ if ! test -f fail; then
         rm -f $test.\$ref
     fi
   else
-    cp -f $log fail
-  fi
-  if ! test -f fail; then
-    touch pass
+    if ! test -s $log; then
+       echo "The code timed out after one hour." > $log
+    fi
+    sed "s/^$chksum: //g" $log > fail
   fi
 fi
-rm -f $test $test.c $test.sh $test.*ref
+rm -f $chksum $src $chksum.sh $test.*ref
 tar czf \$HOME/$chksum.tgz *
 rm -r -f \$HOME/$chksum
 EOF
     tar czf $chksum.tgz $chksum
-    rm -r -f $chksum
+    rm -r -f $chksum/
 
     if ! ( scp $chksum.tgz $rhost: && rm -f $chksum.tgz && \
-	ssh $rhost bash -c "\"tar xmzf $chksum.tgz && cd $chksum && tsp -N \$(test \$(tsp -S) -le $NCORES && echo \$(tsp -S) || echo $NCORES) -n nice -19 sh $test.sh\" && sleep 0 && tsp -p && tsp -w" > tspid.$ext && \
-	scp -q $rhost:$chksum.tgz $chksum.tgz && \
-	ssh $rhost rm -r -f $chksum.tgz && \
-	tar xmzf $chksum.tgz && \
-	rm -f $chksum.tgz $test.c $test.*ref ) > /dev/null 2>> ssh.log;
+	       ssh $rhost bash -c "\"tar xmzf $chksum.tgz && cd $chksum && tsp -N \$(test \$(tsp -S) -le $NCORES && echo \$(tsp -S) || echo $NCORES) -n nice -19 sh $chksum.sh\" && sleep 0 && echo $chksum && tsp -w" > tspid.$ext && \
+	       scp -q $rhost:$chksum.tgz $chksum.tgz && \
+	       ssh $rhost rm -r -f $chksum.tgz && \
+	       tar xmzf $chksum.tgz && \
+	       rm -f $chksum.tgz $src $test.*ref progress) > /dev/null 2>> ssh.log;
+    then
+	cat ssh.log >> fail
+    fi
+    rm -f ssh.log
+
+    # generate graphics
+    doplots "$test"
+    
+    if test -f fail; then
+	if test -f ../$test.$ext; then
+	    mv -f ../$test.$ext fail.$ext
+	else
+	    short=`echo $test | sed 's/^~//'`
+	    test -f ../$short.$ext && mv -f ../$short.$ext fail.$ext
+	fi
+	echo
+	echo \[$test.$ext\]
+	cat fail
+    else
+	touch pass
+    fi
+    # Complete
+    rm -f *pid.$ext completing
+}
+
+# compile/run on a remote "sandbox" (OCTAVE)
+remotely_octave()
+{
+    rhost=$1
+    chksum=`(cat $test.s && pwd && echo $test) | $GENSUM | cut -d' ' -f1`.$ext
+    mkdir $test/$chksum
+    cd $test
+    run=`echo $test | sed 's/^~//'`
+    if test "$run" != "$test"; then
+	cp -f $run.* $chksum 2> /dev/null || true
+    fi
+    cp -f $test.* $chksum 2> /dev/null || true
+    rm -f $chksum/$src.html
+    if test `echo "$test" | sed 's/^~//'` != "$test"; then
+	cd $chksum
+	for f in "$test".*; do
+	    mv -f "$f" `echo "$f" | sed 's/^~//'`
+	done
+	cd ..
+    fi
+    mkdir $chksum/lib/
+    cp -f ../*.m $chksum/lib/
+    cp -f ../$src $chksum/$src
+    cat <<EOF >$chksum/$chksum.sh
+#!/bin/sh
+
+run_untrusted()
+{
+  status=0
+  notrust=/tmp/$chksum
+  if ! sudo -n -u basilisk-untrusted -- bash -c "source /home/basilisk/.bashrc && mkdir \$notrust && cp -arf * \$notrust && cd \$notrust && rm -f completing && \$1 && touch completing"; then
+     status=1
+  fi
+  if ! cp -arf \$notrust/* .; then
+     status=1
+  fi
+  sudo -n -u basilisk-untrusted -- rm -rf \$notrust/
+  return \$status
+}
+
+pass=true
+if ! run_untrusted "$TIMEOUT octave-cli --path lib -W -H -q $src 2> $log > $out"; then
+    pass=false
+fi
+
+if \$pass; then
+    if test -f $test.$ref; then
+      ref=$ref
+    else
+      ref=ref
+    fi
+    if test -f $test.\$ref; then
+        echo diff $log $test.\$ref > fail
+        diff $log $test.\$ref >> fail && rm -f fail
+        rm -f $test.\$ref
+    fi
+else
+    if ! test -s $log; then
+       echo "The code timed out after one hour." > $log
+    fi
+    cp -f $log fail
+fi
+if ! test -f fail; then
+    touch pass
+fi
+rm -r -f $chksum $src $chksum.sh $test.*ref lib/
+tar czf \$HOME/$chksum.tgz *
+rm -r -f \$HOME/$chksum
+EOF
+    tar czf $chksum.tgz $chksum
+    rm -r -f $chksum/
+
+    if ! ( scp $chksum.tgz $rhost: && rm -f $chksum.tgz && \
+	       ssh $rhost bash -c "\"tar xmzf $chksum.tgz && cd $chksum && tsp -n nice -19 sh $chksum.sh\" && sleep 0 && echo $chksum && tsp -w" > tspid.$ext && \
+	       scp -q $rhost:$chksum.tgz $chksum.tgz && \
+	       ssh $rhost rm -r -f $chksum.tgz && \
+	       tar xmzf $chksum.tgz && \
+	       rm -f $chksum.tgz $src $test.*ref progress) > /dev/null 2>> ssh.log;
     then
 	cat ssh.log >> fail
     fi
     rm -f ssh.log
 
     if test -f fail; then
-	mv -f ../$test.$ext fail.$ext
+	if test -f ../$test.$ext; then
+	    mv -f ../$test.$ext fail.$ext
+	else
+	    short=`echo $test | sed 's/^~//'`
+	    test -f ../$short.$ext && mv -f ../$short.$ext fail.$ext
+	fi
 	echo
 	echo \[$test.$ext\]
 	cat fail
-	if test -n "$MAINTAINER"; then
-	    (
-		echo Latest change:
-		echo
-		darcs changes --last=1
-		echo
-		if test -f ../$test.c.page; then
-		    cat <<EOF
-See http://basilisk.fr/$dir/$test.c
-EOF
-		else
-		    cat fail
-		fi 
-	    ) | mail -s "basilisk: $test.$ext failed" $MAINTAINER
-	fi
-    fi
-    cd ..
-    # generate graphics
-    if test -f $test.plot -o -f $test.plot.page; then
-	if ! make $test/plot.png > $test/.tmp 2>&1; then
-	    cat $test/.tmp >> warn
-	fi
-    fi
-    cd $test
-    if ! sh $BASILISK/gnuplot.sh > .tmp; then
-	cat .tmp >> warn
+    else
+	touch pass
     fi
     # Complete
-    rm -f *pid.$ext .tmp
-    expirecache
+    rm -f *pid.$ext completing
 }
 
 checksum()
@@ -232,57 +424,89 @@ checksum()
     fi
 }
 
-# check sum for test.c
+# check sum for $src
 source_modified=false
-if ! test -f $test.$ext || ! checksum $test.c $test.$ext; then
+if ! test -f $test.$ext || ! checksum $src $test.$ext; then
     source_modified=true
 fi
+
+killchildren()
+{
+    p=$1
+    c=`ps -o pid= --ppid $p`
+    kill $p
+    while test -n "$c"; do
+	p=$c
+	c=`ps -o pid= --ppid $p`
+	kill $p
+    done
+}
 
 # check sum for test.s
 if test -f $test.$ext && checksum $test.s $test.$ext; then
     touch $test.$ext
     echo "make: '$test.$ext' is up to date."
-    if test -n "$SANDBOX" && $source_modified; then
-	rm -f $test/warn && make $test/plots
+    if $source_modified; then
+	if test -n "$SANDBOX"; then
+	    rm -f $test/warn
+	    awk -f $BASILISK/gnuplot.awk < $src > $test/plots
+	    awk -f $BASILISK/python.awk < $src > $test/plots.py
+	    chksum=`(cat $test.s && pwd && echo $test) | $GENSUM | cut -d' ' -f1`.$ext
+	    cd $test
+	    doplots "$test"
+	    cd ..
+	fi
+	$GENSUM $src $test.s > $test.$ext
     fi
 # check sum for test.s in fail.tst
-elif ! test -f $test/fail.$ext || ! checksum $test.s $test/fail.$ext; then
+elif ! test -f $test/fail.$ext || ! test -f $test/fail || ! checksum $test.s $test/fail.$ext; then
     if test -n "$SANDBOX" -a -f $test/pid.$ext; then
-	echo Killing `cat $test/pid.$ext`
-	kill `cat $test/pid.$ext`
-	ssh $SANDBOX kill `cat $test/tspid.$ext`
+	killchildren `cat $test/pid.$ext`
+	if test -f $test/tspid.$ext; then
+	    ssh $SANDBOX killtest `cat $test/tspid.$ext`
+	fi
 	rm -f $test/*pid.$ext
     fi
 
     rm -f $test.$ext $test/pass \
-	$test/fail $test/fail.* $test/warn $test/plot.png $test/plots $test/core
-    $GENSUM $test.c $test.s > $test.$ext
-    expirecache
+	$test/fail $test/fail.* $test/plot.png $test/plots $test/core
+    $GENSUM $src $test.s > $test.$ext
 
-    mkdir -p $test && cp -f $test.c $test
-    awk -f $BASILISK/gnuplot.awk < $test.c > $test/plots
+    mkdir -p $test && cp -f $src $test
+    awk -f $BASILISK/gnuplot.awk < $src > $test/plots
+    awk -f $BASILISK/python.awk < $src > $test/plots.py
     cp -f $test.* $test 2> /dev/null || true
-    rm -f $test/*.[sd] $test/*.*tst $test/$test.c.page 2> /dev/null || true
-    if test -d $BASILISK_WIKI/static -a -f $test.c.page; then
-	if test ! -L $BASILISK_WIKI/static/$dir/$test; then
-	    mkdir -p $BASILISK_WIKI/static/$dir
-	    ln -s $PWD/$test $BASILISK_WIKI/static/$dir/$test
-	fi
+    run=`echo $test | sed 's/^~//'`
+    if test "$run" != "$test"; then
+	cp -f $run.* $test 2> /dev/null || true
     fi
+    rm -f $test/*.[sd] $test/*.*tst $test/$src.html 2> /dev/null || true
 
     if test -n "$SANDBOX"; then
-        ( remotely $SANDBOX ) &
+	case "$src" in
+	    *.c) ( remotely $SANDBOX ) & ;;
+	    *.m) ( remotely_octave $SANDBOX ) & ;;
+	esac
 	echo $! > $test/pid.$ext
 	sleep 1
     else
-	locally
-	rm -f $test/plots
+	case "$src" in
+	    *.c) locally ;;
+	    *.m) locally_octave ;;
+	esac
+	rm -f $test/plots $test/plots.py
     fi
 fi
 
 if test -f $test/fail; then
     cat $test/fail
-    rm -f $test.$ext
+    if test -f $test.$ext; then
+	if test -n "$SANDBOX"; then
+	    mv -f $test.$ext $test/fail.tst
+	else
+	    rm -f $test.$ext $test/fail.tst
+	fi
+    fi
     exit 1
 elif test -f $test/pid.$ext; then
     echo \[$test.$ext on $SANDBOX \(`cat $test/pid.$ext`\)\]
